# -*- coding: utf-8 -*-
"""Assignment-1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ScO_Rh9QAWKaSjyWAWDPaeefI2DlLE_A

Task 1 - Create a pandas dataframe (DataFrame name as 'df') (10 observation and 5 features)
"""

import pandas as pd
d = {"Chocolate":["Kinder Joy","Kit-Kat","Milky Bar","Dairy Milk","Kisses","Toblerone","Ferrero Rocher","5-Star","m&m's","Snickers"],
     "Brand":["Ferrero","Nestle","Nestle","Cadbury","Hershey's","Toblerone","Ferrero","Cadbury","M&M's","Mars"],
     "Price(Rs)":[45,30,20,85,50,225,149,20,120,50],
     "Weight(g)":[20,38.5,38,60,36,100,50,40,45,45],
     "Sugar Content(g)":[10,15.1,18.7,33.3,16.5,56,20,24.4,30,22.1]}
df = pd.DataFrame(d)
df

"""Task 2 - Check the info of 'df'"""

df.info()

"""Task 3 - Check the descriptive statistics of 'df'"""

df.describe()

"""Task 4 - check the 4th index observation with 'loc' slicing operator."""

df.loc[4]

"""Task 5 - Check the null values in your 'df'"""

df.isnull().any()